folio-org/ui-data-export

- CHANGELOG.md
- package.json
Updated 
`stripes` to `v3.0.0`, 
`stripes-core` to `4.0.0`,
`react-intl` to `2.9.0`
[UIDEXP-30](https://issues.folio.org/browse/UIDEXP-30)
Please, update your core `package.json`:
```javascript
"dependencies": {
"@folio/stripes": "^3.0.0"
},
"resolutions": {
"@folio/stripes": "^3.0.0"
}
```
If you use `stripes-sample-platform`, please, update `package.json` here too:
```javascript
"dependencies": {
"@folio/stripes": "^3.0.0"
}
```
> UIDEXP-30: Update stripes to v3.0.0

- CHANGELOG.md
- package.json
- src/components/QueryFileUploader/QueryFileUploader.js
1. Set dependency on the "data-export": "1.0" backend interface
2. Prevent generating of client ID for initiation export job request (It turned out requests created with the help of manifest generate it by default. In order to prevent it `clientGeneratePk: false` should be used for the resource) as it causes error response on the server about the unexpected `id` field.
[UIDEXP-20](https://issues.folio.org/browse/UIDEXP-20)
> UIDEXP-20: Set dependency on the "data-export" backend interface

- CHANGELOG.md
- package.json
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
- test/bigtest/tests/jobLogs-test.js
Populate Job Id in "Running jobs" and "Logs" components on the landing page.
[UIDEXP-35](https://issues.folio.org/browse/UIDEXP-35)
> UIDEXP-35: Populate hrId fields

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
- test/bigtest/network/scenarios/fetch-job-profiles-success.js
- test/bigtest/tests/jobLogs-test.js
Populate Run by in "Running jobs" and "Logs" components on the landing page.
[UIDEXP-37](https://issues.folio.org/browse/UIDEXP-37)
> UIDEXP-37: Populate runBy on Job logs & Running jobs

- CHANGELOG.md
- src/components/QueryFileUploader/QueryFileUploader.js
- src/routes/Home.js
- src/settings/MappingProfiles/MappingProfiles.js
- test/bigtest/interactors/settings/index.js
- test/bigtest/interactors/settings/mappingProfilesInteractor.js
- test/bigtest/tests/mappingProfiles-test.js
- test/bigtest/tests/settings-test.js
Add static search form on field mapping profiles settings page in the scope of the [UIDEXP-40](https://issues.folio.org/browse/UIDEXP-40).
> UIDEXP-40: Add static search form on field mapping profiles settings page

- CHANGELOG.md
- src/routes/Home.js
Retrieve only the latest logs on landing page in the scope of the [UIDEXP-56](https://issues.folio.org/browse/UIDEXP-56).
> UIDEXP-56: Retrieve only latest logs on landing page

- CHANGELOG.md
- package.json
Provide missing "module.data-export.enabled" permission in the scope of the [UIDEXP-67](https://issues.folio.org/browse/UIDEXP-67).
> UIDEXP-67: Provide missing "module.data-export.enabled" permission

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
Handle case when 'progress' field is missing from log detail in the scope of [UIDEXP-68](https://issues.folio.org/browse/UIDEXP-68).
> UIDEXP-68: Handle case when 'progress' field is missing from log detail

- CHANGELOG.md
- src/routes/Home.js
- test/bigtest/interactors/jobs/JobLogsContainerInteractor.js
- test/bigtest/tests/jobLogs-test.js
- translations/ui-data-export/en.json
Add the "View all" button to the pane header to navigate to the all logs view. [Story](https://issues.folio.org/browse/UIDEXP-62).
The navigation should be implemented in scope of the separated story according to the requirements.
> UIDEXP-62: Add button to navigate to all logs view

- CHANGELOG.md
- src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.css
- src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.js
Update jobs list structure according to the accessibility requirements in the scope of [UIDEXP-49](https://issues.folio.org/browse/UIDEXP-49).
Make sure that immediate children of `<ul>` tags be `<li>` elements.
> UIDEXP-49: Update jobs list structure according to the accessibility requirements

- CHANGELOG.md
- package.json
- src/components/QueryFileUploader/QueryFileUploader.js
- src/settings/DataExportSettings/DataExportSettings.js
- src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
- src/settings/JobProfiles/JobProfilesForm/JobProfilesForm.js
- src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
- src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
- src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
- src/settings/MappingProfiles/MappingProfilesForm/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesForm/TransformationsField/index.js
- src/settings/MappingProfiles/MappingProfilesForm/TransformationsField/processTransformations.js
- src/settings/MappingProfiles/MappingProfilesForm/TransformationsField/transformations.json
- src/settings/MappingProfiles/NewMappingProfileFormRoute/NewMappingProfileFormRoute.js
- src/utils/constants.js
- test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/interactors/MappingProfilesFormInteractor.js
- test/bigtest/tests/units/settings/MappingProfilesForm/interactors/TransformationsInteractor.js
- test/bigtest/tests/units/settings/MappingProfilesForm/mappingProfilesTransformations-test.js
- translations/ui-data-export/en.json
Implement mapping profiles form transformation fields in the scope of the [UIDEXP-47](https://issues.folio.org/browse/UIDEXP-47).
`FieldArray` from `react-final-form-arrays` in conjunction with MCL. Filed operates with `order` prop to be able in the future to do sorting and searching properly. Fields such as `order` and `displayName` should eventually be removed before sending a request to the server. `normalizeTransformationFormValues` should be used for that.
> UIDEXP-47: Implement mapping profiles form transformation fields

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- test/bigtest/network/scenarios/fetch-job-executions-success.js
- test/bigtest/tests/jobLogs-test.js
- translations/ui-data-export/en.json
Add 'Errors' column to the list of completed jobs on the main page
[UIDEXP-97](https://issues.folio.org/browse/UIDEXP-97)
> UIDEXP-97: Add Error column to the list of completed jobs

- src/settings/MappingProfiles/MappingProfilesForm/TransformationsField/transformations.json
Provide correct mapping transformations path for "electronicAccess.linkText" in the scope of [UIDEXP-47](https://issues.folio.org/browse/UIDEXP-47).
> UIDEXP-47: Provide correct mapping transformations path for "electronicAccess.linkText"

- CHANGELOG.md
- src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
- test/bigtest/interactors/jobs/RunningJobsInteractor.js
- test/bigtest/network/scenarios/fetch-job-executions-success.js
- test/bigtest/tests/jobs-test.js
The user info can't be provided in some cases according to the latests information. So the check is added to prevent the main page crashing and updated tests. [Issue](https://issues.folio.org/browse/UIDEXP-107).
> UIDEXP-107: Fix error screen display in case of missed user information in job executions

- CHANGELOG.md
- src/settings/DataExportSettings/DataExportSettings.js
- test/bigtest/interactors/settings/SettingsSectionsPaneInteractor.js
- test/bigtest/tests/settings-test.js
- translations/ui-data-export/en.json
Add a description to the profiles info and update link to the data export specific page. [Story](https://issues.folio.org/browse/UIDEXP-53)
> UIDEXP-53: Update description and link in profiles info on the second settings pane

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- test/bigtest/tests/units/settings/MappingProfileDetails/MappingProfileDetails-test.js
Display user name while viewing the mapping profile summary accordion in the scope of the [UIDEXP-109](https://issues.folio.org/browse/UIDEXP-115).
> UIDEXP-109: Display user name while viewing the mapping profile summary accordion

- CHANGELOG.md
- package.json
- translations/ui-data-export/en.json
Add translations for permission names in the scope of the [UIDEXP-76](https://issues.folio.org/browse/UIDEXP-76).
> UIDEXP-76: Add translations for permission names

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- test/bigtest/tests/settings-test.js
Use path instead of id for transformations search to fix labels display. [Issue](https://issues.folio.org/browse/UIDEXP-118)
Additionally I handled issue with broken unit tests.
> UIDEXP-118: Fix transformation labels display on mapping details view page

- CHANGELOG.md
- package.json
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/JobLogsContainer/jobLogsContainer.css
The next changes were added to handle long file names in job logs ([Story](https://issues.folio.org/browse/UIDEXP-121)):
- moved to the static size of the "File name" column (it was agreed with @VictorSoroka1)
- changed button border radius 
- updated labels' settings to support long files name in job logs
**Note**: I have to update react-intl version to avoid broken changes https://github.com/formatjs/formatjs/issues/1744.
> UIDEXP-121: Add long file names handling in job logs

- CHANGELOG.md
- package.json
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/JobLogsContainer/jobLogsContainer.css
- translations/ui-data-export/en.json
Update translation of the drag and drop area. [Issue
](https://issues.folio.org/browse/UIDEXP-123)
**Additional changes:** 
- Fix file name (disabled case) padding in job logs
- Unpin react-intl version according to broken changes fixing in 4.7.2
> UIDEXP-123: Fix drag and drop area translation

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
- test/bigtest/network/factories/job-execution.js
- test/bigtest/network/scenarios/fetch-job-executions-success.js
- test/bigtest/tests/jobs-test.js
Add job name display in job logs and executions. [Story](https://issues.folio.org/browse/UIDEXP-116)
Updated tests according to changes in backend responses format
> UIDEXP-116: Add job name display in job logs and executions

- CHANGELOG.md
- src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
- src/settings/JobProfiles/JobProfileDetailsActionMenu/JobProfileDetailsActionMenu.js
- src/settings/JobProfiles/JobProfileDetailsActionMenu/index.js
- src/settings/JobProfiles/JobProfileDetailsRoute/JobProfileDetailsRoute.js
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- src/utils/constants.js
- test/bigtest/network/scenarios/fetch-job-profiles-success.js
- test/bigtest/tests/job-profiles/jobProfileDetails-test.js
- test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetails-test.js
- test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetailsRoute-test.js
- test/bigtest/tests/units/settings/JopProfileDetails/interactors/JobProfileDetailsInteractor.js
- test/bigtest/tests/units/settings/MappingProfileDetails/interactors/TransformationsInteractor.js
Implement a job profile actions menu in the scope of the [UIDEXP-84](https://issues.folio.org/browse/UIDEXP-84).
> UIDEXP-84: Implement job profile details actions menu

- CHANGELOG.md
- src/components/ChooseJobProfile/ChooseJobProfile.js
- src/components/JobLogsContainer/JobLogsContainer.js
- src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
- src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
Fix accessibility string building for used MCL based pages: MappingProfiles, JobProfiles, JobLogs. [Bug](https://issues.folio.org/browse/UIDEXP-117).
> UIDEXP-117: Fix accessibility string building for MCL components

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.css
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- test/bigtest/network/scenarios/fetch-mapping-profiles-success.js
- test/bigtest/tests/units/settings/MappingProfileDetails/MappingProfileDetails-test.js
I wrapped transformations value by `<pre>` tag to support several spacing on mapping profile details page. [Bug](https://issues.folio.org/browse/UIDEXP-129).
> UIDEXP-129: Fix spacing display of Transformation fields on mapping profile view page

- CHANGELOG.md
- package.json
Update module version and changelog after bugfix v2.0.1 release in the scope of the [UIDEXP-125](https://issues.folio.org/browse/UIDEXP-125).
> UIDEXP-125: Update module version and changelog after bugfix v2.0.1 release

- .eslintrc
- CHANGELOG.md
- src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
- src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.css
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/SearchForm.css
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/SearchForm.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/index.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
- src/settings/MappingProfiles/RecordTypeField/RecordTypeField.js
- src/settings/MappingProfiles/RecordTypeField/index.js
- test/bigtest/helpers/translationsProperties.js
- test/bigtest/interactors/PaneInteractor.js
- test/bigtest/interactors/index.js
- test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsModal-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/interactors/TransformationsModalInteractor.js
Implement record type filter behavior in add mapping profile transformations modal in the scope of the [UIDEXP-69](https://issues.folio.org/browse/UIDEXP-69).
- Move search form markup to its own `SearchForm` component;
- Move reusable logic for record type field to its own `RecordType` component;
- Reset filters upon modal closing;
- `MappingProfilesTransformationsModal` calculates `searchResults` so the subheader can display the proper amount of search results;
- Extend `TransformationsForm` with `searchResults` prop so filtering logic can be done;
- Filter pane visibility state is now done via CSS only so the filters state can be preserved when it is hidden and displayed again. Since `Pane` component does not properly deal with this, the `style` for this is conditionally applied to it …
> UIDEXP-69: Implement record type filter behavior in add mapping profile transformations modal

- CHANGELOG.md
- src/settings/ProfileDetails/ProfileDetails.js
Accommodate `FullScreenView` component usage according to [changes in stripes-data-transfer-components](https://github.com/folio-org/stripes-data-transfer-components/pull/88/files)l in the scope of the [UIDATIMP-535](https://issues.folio.org/browse/UIDATIMP-535).
> UIDATIMP-535: Accommodate `FullScreenView` component usage

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.css
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
- src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/processTransformations.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
- src/settings/MappingProfiles/NewMappingProfileFormRoute/NewMappingProfileFormRoute.js
- src/settings/MappingProfiles/TransformationsList/TransformationsList.css
- src/settings/MappingProfiles/TransformationsList/TransformationsList.js
- src/settings/MappingProfiles/TransformationsList/index.js
- test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetails-test.js
- test/bigtest/tests/units/settings/MappingProfileDetails/MappingProfileDetails-test.js
- test/bigtest/tests/units/settings/MappingProfileDetails/interactors/TransformationsInteractor.js
- test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsModal-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/interactors/MappingProfilesFormInteractor.js
- test/bigtest/tests/units/settings/MappingProfilesForm/mappingProfilesTransformationsUtils-test.js
- translations/ui-data-export/en.json
Add transformations saving  in scope of [story](https://issues.folio.org/browse/UIDEXP-73). The next changes were added to support needed functionality:
- Add selected transformations saving and transition to the mapping profile form
- Move transformations list view to the shared component
- Replace TransformationsField solution by shared component to display selected transformations on the mapping profile form
- Add success callout display after transformations saving
**Note**: I have to disable several tests while [STCOR-445](https://github.com/folio-org/stripes-core/pull/896) is not handled
> UIDEXP-73: Implement transformations saving

- CHANGELOG.md
- test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
- test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsModal-test.js
Add tests to cover closing functionality of mapping profile form. [Issue](https://issues.folio.org/browse/UIDEXP-99).
> UIDEXP-99: Cover closing functionality of mapping profile form by tests

- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
- test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
Handle the case when form should be valid when no filled transformations are present in the scope of the [UIDEXP-138](https://issues.folio.org/browse/UIDEXP-138).
> UIDEXP-138: Handle the case when form should be valid when no filled transformations are present

- CHANGELOG.md
- src/components/ErrorLogsView/ErrorLogsView.js
- src/components/ErrorLogsView/index.js
- src/components/JobLogsContainer/JobLogsContainer.js
- src/index.js
- test/bigtest/tests/errorLogs-test.js
Add transition to the error logs view on job logs item click (if there are errors). [Story](https://issues.folio.org/browse/UIDEXP-180)
**Note**: There are no ways to cover the transtion to the new tab using BigTest.
> UIDEXP-18: Implement transtion to error logs page

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
Fix mapping profile form validation in case of empty transformation values. Now this case should be marked as valid. [Issue](https://issues.folio.org/browse/UIDEXP-166).
> UIDEXP-166: Fix mapping profile form validation in case of empty transformation values

- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/TransformationsList/TransformationsList.js
After implementing [UIDEXP-162](https://issues.folio.org/browse/UIDEXP-162) a bug was found, when mapping profile transformations form was not sorted, when mapping profile was created via API call. 
Mapping profile that was created via API call
> UIDEXP-162: Fix mapping profile transformations form not being sorted when created via API

- CHANGELOG.md
- src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
Fix date and time display in Safari using FormattedDate and FormattedTime components from stripes-components instead of react-intil. [Story](https://issues.folio.org/browse/UIDEXP-175).
> UIDEXP-175: Fix date and time display in Safari

- CHANGELOG.md
- package.json
Release v3.0.0 of ui-data-export in the scope of [UIDEXP-173](https://issues.folio.org/browse/UIDEXP-173).
> UIDEXP-173: Release v3.0.0

- CHANGELOG.md
- src/settings/JobProfiles/CreateJobProfileRoute/CreateJobProfileRoute.js
- src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.js
- src/settings/MappingProfiles/EditMappingProfileRoute/EditMappingProfileRoute.js
- src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
- src/settings/ProfileDetails/ProfileDetails.js
- src/settings/utils/useProfileHandlerWithCallout.js
- test/bigtest/tests/units/settings/EditMappingProfileRoute/EditMappingProfileRoute-test.js
[[UIDEXP-167]](https://issues.folio.org/browse/UIDEXP-167)
After clicking `Save & Close` button on Edit mapping profile page it should close the mapping profile details page and navigate to mapping profile list.
> UIDEXP-167: Fix Save & Close button on the Edit mapping profile page not closing the profile

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
- test/bigtest/network/scenarios/fetch-job-executions-success.js
- test/bigtest/tests/jobLogs-test.js
[[UIDEXP-182]](https://issues.folio.org/browse/UIDEXP-182)
The user was unable to view error logs for job, that was triggered by an empty file.
> UIDEXP-182: Fix inability to view error logs for an empty file

- CHANGELOG.md
- package.json
- test/bigtest/tests/units/ErrorLogs/ErrorLogs-test.js
- test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetails-test.js
- test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetailsRoute-test.js
- test/bigtest/tests/units/settings/MappingProfileDetails/MappingProfileDetails-test.js
Bump `babel-eslint` to `v10.0.3`, adjust tests after updates to `Preloader` interactor.
> UIDATIMP-580: Bump babel-eslint to v10.0.3, adjust test after updates to Preloader

- CHANGELOG.md
- src/components/JobLogsContainer/JobLogsContainer.js
In the sope of [UIDEXP-208](https://issues.folio.org/browse/UIDEXP-208).
For some edge cases, the progress field for job log is not provided, which causes UI to break. This PR prevents UI from breaking.
> UIDEXP-208: Handle missing job progress field

- CHANGELOG.md
- package.json
Update module version and changelog after bugfix v3.0.1 release in the scope of the [UIDEXP-201](https://issues.folio.org/browse/UIDEXP-201).
> UIDEXP-207: Update module version and changelog after bugfix v3.0.2 release

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
In the scope of [UIDEXP-209](https://issues.folio.org/browse/UIDEXP-209).
When saving mapping profile with SRS and Holdings or/and Item record types, the form did not pass the validation. This PR fixes the issue.
> UIDEXP-209: Fix inability to create mapping profile with SRS and Holdings/Item types

- CHANGELOG.md
- package.json
Move pretender to dev dependencies in the scope of the [UIDEXP-186](https://issues.folio.org/browse/UIDEXP-186).
> UIDEXP-186: Move pretender to dev dependencies

- src/settings/MappingProfiles/CheckboxGroupField/CheckboxGroupField.js
In scope of [UIDEXP-187](https://issues.folio.org/browse/UIDEXP-187)
Replace `Row` component with `Layout`, as Row was sticking out of the container.
> UIDEXP-187: Replace Row component with Layout in CheckboxGroupField

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/processRawTransformations.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/processRawTransformations.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.css
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/validateTransformations.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/validateTransformations.test.js
- test/bigtest/tests/units/settings/EditMappingProfileRoute/EditMappingProfileRoute-test.js
- test/jest/helpers/getTransformationFieldGroups.js
- translations/ui-data-export/en.json
In scope of [UIDEXP-187](https://issues.folio.org/browse/UIDEXP-187).
Provided data entry validation for each element of the transformation text boxes.
**Validation rules:** 
1. MARC field should only contain 3 digits - this field is **required**.
2. Indicator fields can contain a single digit, letter, whitespace or be empty.
3. Subfield should start with **$** and be followed by single letter or one or two digits.
4. Transformations with **Instance**record type allowed to be empty.
**Validation scenarios:**
- Should occur for every filled and/or checked transformation on sumbit.
- In case of failed validation, every failed transformation should have a red mark.
-  In case of failed validation, submit button should be disabled until some changes were made to the transformation form
> UIDEXP-187: Add validation to the transformation elements

- CHANGELOG.md
- src/components/ErrorLogsView/utils/generateAffectedRecordInfo.js
- src/components/ErrorLogsView/utils/generateAffectedRecordInfo.test.js
- src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
Display title only for instances on error logs page in the scope of the [UIDEXP-211](https://issues.folio.org/browse/UIDEXP-211).
> UIDEXP-211: Display title only for instances on error logs page

- CHANGELOG.md
- src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/validateTransformations.js
In the scope of [UIDEXP-217](https://issues.folio.org/browse/UIDEXP-217).
Fix incorrect field validation when clearing send from backend transformation that has empty indicators in it.
> UIDEXP-217: Fix incorrect field validation when clearing filled transformation

- CHANGELOG.md
- src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.css
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/validateTransformations.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/validateTransformations.test.js
- test/jest/helpers/getTransformationFieldGroups.js
In the scope of [UIDEXP](https://issues.folio.org/browse/UIDEXP-220).
After the validation fails, the user can be notified which field contains incorrect data by highlighting the textbox with invalid data.
> UIDEXP-220: Add a visual cue to invalid entry on transformation form

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
In the scope of [UIDEXP-218](https://issues.folio.org/browse/UIDEXP-218).
When the user adjusts their input after verification fails, the input should become valid. In case, when the last invalid field is adjusted, the transformation group should also hide the invalid icon.
> UIDEXP-218: Clear the validation error after user adjusts data entry in transformation field

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.js
- src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
- test/jest/helpers/getTransformationFieldGroups.js
Add placeholder to the transformation form in the scope of the [UIDEXP-219](https://issues.folio.org/browse/UIDEXP-219).
> UIDEXP-219: Add placeholder to the transformation form

- CHANGELOG.md
- src/components/ErrorLogsView/ErrorLogsView.test.js
- src/components/ErrorLogsView/utils/generateAffectedRecordInfo.js
- src/components/ErrorLogsView/utils/generateAffectedRecordInfo.test.js
- test/bigtest/fixtures/errorLogs.js
- translations/ui-data-export/en.json
When the export of the record fails, the user will need to investigate the reason for it. In order to make the navigation between logs and the affected record easier, the link to the inventory record will need to be created.
> UIDEXP-203: Display a link to the inventory record on Error logs page

- CHANGELOG.md
- package.json
Update `stripes-cli` to `v2.0.0` in the scope of the [UIDEXP-227](https://issues.folio.org/browse/UIDEXP-227).
> UIDEXP-227: Update `stripes-cli` to `v2.0.0`

- .gitignore
- CHANGELOG.md
- src/settings/JobProfiles/CreateJobProfileRoute/CreateJobProfileRoute.js
https://issues.folio.org/browse/UIDEXP-241 …
> UIDEXP-241 Mapping profiles list not ordered alphabetically on the new job profile form

- CHANGELOG.md
- package.json
react-virtualized-auto-sizer is incorrectly listed as a peer-dependency
[UIDEXP-290](https://issues.folio.org/browse/UIDEXP-290)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule …
> UIDEXP-290: react-virtualized-auto-sizer is incorrectly listed as a peer-dependency

- CHANGELOG.md
- package.json
- test/jest/babel.config.js
- translations/ui-data-export/en.json
https://issues.folio.org/browse/UIDEXP-321 …
> UIDEXP-321 Update translations in logs list

- package.json
- src/components/ProfileDetailsActionMenu/ProfileDetailsActionMenu.js
- src/settings/ProfileDetails/ProfileDetails.js
[UIDEXP-304](https://issues.folio.org/browse/UIDEXP-304)
Here we hide the action menu if user have only view permission. In prev implementation, we were disabling buttons in action menu.  All other implementation was done before in scope of that ticket
Can't make a video since perms not working locally.
> UIDEXP-304: Need new permission(s) to view Data Export settings in UI

- package.json
https://folio-org.atlassian.net/browse/UIDEXP-351
Here small fix to an existing story.
> UIDEXP-351: Cannot view Mapping profiles and Job profiles with "Settings (Data export): display list of settings pages" permission

- CHANGELOG.md
- src/hooks/useDefaultSorting.js
After this PR is merged, conflicts with search parameters will no longer arise since they will be cleared when the component is unmounted. Ref [UIDEXP-366](https://folio-org.atlassian.net/browse/UIDEXP-366)
> UIDEXP-366 Error message is displayed when go from Data export Settings to View All page

- src/hooks/useDefaultSorting.js
As a part of https://github.com/folio-org/ui-data-export/pull/447 all search parameters were cleaned after component unmount, but it have to be only for sort-related parameters.
Note: CHANGELOG.MD was updated in initial PR
> UIDEXP-366 Clean only sort related search params

- CHANGELOG.md
- src/components/ChooseJobProfile/ConfirmationModal/ConfirmationModal.js
- src/index.js
- src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
- src/settings/MappingProfiles/CheckboxGroupField/CheckboxGroupField.js
- src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
- src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
- src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
- src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
- src/settings/MappingProfiles/TransformationsList/TransformationsList.js
After this PR merged all default props will be replaced using default values syntax. More info https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-deprecated-react-apis
Refs: [UIDEXP-376](https://folio-org.atlassian.net/browse/UIDEXP-376)
> UIDEXP-376 React v19: refactor away from default props for functional components

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
- translations/ui-data-export/en.json
https://folio-org.atlassian.net/browse/UIDEXP-377
Here we added an info tip to the suppress field title.
https://github.com/folio-org/ui-data-export/assets/72550466/b7b7e536-af5a-4858-8574-f33a7c1f17fa
> UIDEXP-377: Add info tip to field suppression

- CHANGELOG.md
- src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
After this PR merged, -  info icon for Fields suppression field will be consistent with another info icons on this form (show on click instead of hover + size change).
> UIDEXP-382 Add consistency to Add mapping profile form

- CHANGELOG.md
- src/components/ErrorLogsView/ErrorLogsView.js
- translations/ui-data-export/en.json
https://folio-org.atlassian.net/browse/UIDEXP-399
Here we added error handling for `error.instance.noPermission`. For now, we receive as `value 3` string, but after https://folio-org.atlassian.net/browse/MDEXP-805 it will be an array, we added `Array.isArray(value) ? value.join(', ') : value;`
The current flow looks like this 
https://github.com/user-attachments/assets/70bd76ef-2c98-4e31-915a-bd167e87b3bc
> UIDEXP-399: Add translation to “error.instance.noPermission” error
