translations/ui-data-export/it_IT.json

Update translation strings as of 20200127T201424

---

translations/ui-data-export/ar.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/pt_BR.json

Update translation strings as of 20200202T214053

---

translations/ui-data-export/ar.json
translations/ui-data-export/es_419.json

Update translation strings as of 20200211T224145

---

CHANGELOG.md
src/components/Jobs/Jobs.css
src/components/Jobs/Jobs.js
src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.css
src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.js
src/components/Jobs/RunningJobs/ItemFormatter/index.js
src/components/Jobs/RunningJobs/JobDetails/JobDetails.js
src/components/Jobs/RunningJobs/JobDetails/index.js
src/components/Jobs/RunningJobs/RunningJobs.js
src/components/Jobs/RunningJobs/index.js
src/components/Jobs/RunningJobs/tempData.js
src/components/Jobs/index.js
src/components/index.js
src/routes/Home.js
src/utils/constants.js
test/bigtest/interactors/index.js
test/bigtest/interactors/jobs/JobsAccordionInteractor.js
test/bigtest/interactors/jobs/JobsInteractor.js
test/bigtest/interactors/jobs/RunningJobInteractor.js
test/bigtest/interactors/jobs/RunningJobsControlButtonsInteractor.js
test/bigtest/tests/jobs-test.js
translations/ui-data-export/en.json

Add running jobs component to display static data in the scope of the [UIDEXP-6](https://issues.folio.org/browse/UIDEXP-6).
**Note:** Some branches will be covered by tests in scope of [UIDEXP-22](https://issues.folio.org/browse/UIDEXP-22) not to make a double effort with a temp data.

UIDEXP-6: Add running jobs components to display temp static data

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200217T172736

---

.eslintrc
CHANGELOG.md
package.json
src/components/QueryFileUploader/QueryFileUploader.js
src/components/QueryFileUploader/utils/generateFileDefinitionBody.js
src/components/QueryFileUploader/utils/index.js
test/bigtest/interactors/queryFileUploaderInteractor.js
test/bigtest/network/config.js
test/bigtest/tests/query-file-uploader-test.js
test/bigtest/tests/units/generateFileDefinitionBody-test.js
translations/ui-data-export/en.json

Initiate the export job process once the user has selected a file in the scope of [UIDEXP-20](https://issues.folio.org/browse/UIDEXP-20).

UIDEXP-20: Initiate the export job process once the user has selected file

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200224T151433

---

CHANGELOG.md
src/components/QueryFileUploader/QueryFileUploader.js
src/components/QueryFileUploader/utils/checkFileHaveCsvExtension.js
src/components/QueryFileUploader/utils/index.js
test/bigtest/interactors/queryFileUploaderInteractor.js
test/bigtest/tests/query-file-uploader-test.js
test/bigtest/tests/units/checkFileHaveCsvExtension-test.js
translations/ui-data-export/en.json

Validating file with UUIDs and display an error message if invalid
[UIDEXP-21](https://issues.folio.org/browse/UIDEXP-21)

UIDEXP-21: Add file csv extension validation

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js
src/components/JobLogsContainer/index.js
src/components/JobLogsContainer/tempData.js
src/components/index.js
src/routes/Home.js
test/bigtest/helpers/index.js
test/bigtest/helpers/prefixKeys.js
test/bigtest/helpers/setup-application.js
test/bigtest/tests/JobLogs-test.js
translations/ui-data-export/en.json

Add job logs display with static data in scope of the [story](https://issues.folio.org/browse/UIDEXP-7)

UIDEXP-7: Add job logs display with static data

---

CHANGELOG.md
src/components/Jobs/RunningJobs/RunningJobs.js
src/contexts/DataFetcherContext.js
src/routes/Home.js
src/utils/constants.js
test/bigtest/interactors/index.js
test/bigtest/interactors/jobs/RunningJobsInteractor.js
test/bigtest/network/config.js
test/bigtest/network/factories/job-execution.js
test/bigtest/network/models/job-execution.js
test/bigtest/network/scenarios/fetch-job-profiles-success.js
test/bigtest/network/serializers/job-execution.js
test/bigtest/tests/jobs-test.js

Implement logic for periodical fetching of running jobs and logs in the scope of [UIDEXP-22](https://issues.folio.org/browse/UIDEXP-22).

UIDEXP-22: Implement logic for periodical fetching of running jobs and logs

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200309T000645

---

translations/ui-data-export/es_419.json

Update translation strings as of 20200312T133304

---

CHANGELOG.md

Release module for the FOLIO 2020Q1. Refs [UIDEXP-26](https://issues.folio.org/browse/UIDEXP-26).

UIDEXP-26: Release v1.0.0

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200314T132532

---

translations/ui-data-export/ar.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/ru.json

Update translation strings as of 20200316T134017

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200331T152557

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js
test/bigtest/network/scenarios/fetch-job-profiles-success.js
test/bigtest/tests/jobLogs-test.js

Populate records field on jobs logs in the scope of the [UIDEXP-36](https://issues.folio.org/browse/UIDEXP-36).

UIDEXP-36: Populate records field on jobs logs

---

CHANGELOG.md
package.json

Update module version changelog after bugfix v1.0.1 release in the scope of the [STDTC-1](https://issues.folio.org/browse/UIDEXP-45).

UIDEXP-45: Update module version changelog after bugfix v1.0.1 release

---

CHANGELOG.md
package.json

Update module version and changelog after bugfix v1.0.2 release in the scope of the [UIDEXP-45](https://issues.folio.org/browse/UIDEXP-45).

UIDEXP-45: Update module version changelog after bugfix v1.0.2 release

---

translations/ui-data-export/pt_BR.json

Update translation strings as of 20200403T124750

---

src/settings/MappingProfilesContainer/tempData.json

Fix static data format for mapping profiles list

UIDEXP-41: Fix static data for mapping profiles list

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200406T162815

---

CHANGELOG.md
src/components/QueryFileUploader/QueryFileUploader.js

Accommodate UI to the change of the export job API endpoint in the scope of the [UIDEXP-44](https://issues.folio.org/browse/UIDEXP-44).

UIDEXP-44: Accommodate UI to the change of the export job API endpoint

---

translations/ui-data-export/pt_BR.json

Update translation strings as of 20200409T134057

---

translations/ui-data-export/ja.json
translations/ui-data-export/zh_CN.json

Update translation strings as of 20200413T183215

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200415T223222

---

translations/ui-data-export/es_419.json
translations/ui-data-export/ja.json

Update translation strings as of 20200420T134821

---

translations/ui-data-export/zh_TW.json

Update translation strings as of 20200423T142657

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200505T210535

---

CHANGELOG.md
package.json

Update to Stripes v4 in the scope of [UIDEXP-101](https://issues.folio.org/browse/UIDEXP-101).

UIDEXP-101: Update to Stripes v4

---

CHANGELOG.md
package.json
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.css
src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.css
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/settings/MappingProfiles/MappingProfilesForm/index.js
src/utils/index.js
src/utils/validation.js
test/bigtest/tests/mapping-profiles/mappingProfilesForm-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/FolioRecordTypeInteractor.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/MappingProfilesFormInteractor.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/SummaryContentInteractor.js
test/bigtest/tests/units/validation-test.js
translations/ui-data-export/en.json

Add mapping profiles form component. [Story](https://issues.folio.org/browse/UIDEXP-46)

UIDEXP-46: Add mapping profiles form

---

CHANGELOG.md
package.json
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/JobProfiles/JobProfilesContainer/tempData.json
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesContainer/tempData.json
test/bigtest/interactors/jobs/JobsInteractor.js
test/bigtest/tests/job-profiles/jobProfiles-test.js
test/bigtest/tests/mapping-profiles/mappingProfiles-test.js
translations/ui-data-export/en.json

Implement job profiles list in the scope of [UIDEXP-80](https://issues.folio.org/browse/UIDEXP-80).

UIDEXP-80: Implement job profiles list

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200515T182823

---

translations/ui-data-export/fr_FR.json
translations/ui-data-export/ru.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200519T123842

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js
test/bigtest/network/scenarios/fetch-job-profiles-success.js
test/bigtest/tests/jobLogs-test.js

Accommodate UI to the changes in `progress` field structure for job execution in the scope of the [UIDEXP-106](https://issues.folio.org/browse/UIDEXP-106).

UIDEXP-106: Accommodate UI to the changes in progress field structure for job execution

---

CHANGELOG.md
package.json
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/JobProfiles/JobProfilesForm/JobProfilesForm.css
src/settings/JobProfiles/JobProfilesForm/JobProfilesForm.js
src/settings/JobProfiles/JobProfilesForm/index.js
src/settings/JobProfiles/NewJobProfileRoute/NewJobProfileRoute.js
src/settings/JobProfiles/NewJobProfileRoute/index.js
test/bigtest/tests/job-profiles/jobProfiles-test.js
test/bigtest/tests/job-profiles/jobProfilesForm-test.js
test/bigtest/tests/units/settings/JobProfilesForm/JobProfilesForm-test.js
test/bigtest/tests/units/settings/JobProfilesForm/interactor.js
test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
translations/ui-data-export/en.json

Add job profiles components and navigation to it. [Story](https://issues.folio.org/browse/UIDEXP-82)

UIDEXP-82: Add job profiles form

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200526T141248

---

translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/pt_BR.json

Update translation strings as of 20200527T144757

---

CHANGELOG.md
package.json
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/settings/MappingProfiles/NewMappingProfileFormRoute/NewMappingProfileFormRoute.js
src/settings/MappingProfiles/NewMappingProfileFormRoute/index.js
test/bigtest/network/config.js
test/bigtest/network/factories/mapping-profiles.js
test/bigtest/tests/mapping-profiles/mappingProfiles-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
translations/ui-data-export/en.json

Integrate new mapping profile form with backend side. [Story](https://issues.folio.org/browse/UIDEXP-88)

UIDEXP-88: Integrate new mapping profile form with backend

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200528T173426

---

CHANGELOG.md
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/JobProfiles/NewJobProfileRoute/NewJobProfileRoute.js
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/utils/useSubmitProfile.js
test/bigtest/network/config.js
test/bigtest/tests/job-profiles/jobProfiles-test.js
translations/ui-data-export/en.json

Integrate new job profiles form with backend and display callouts in success and error cases. [Story](https://issues.folio.org/browse/UIDEXP-85)

UIDEXP-85: Integrate new job profile form with backend

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200602T151309

---

CHANGELOG.md
package.json
src/settings/MappingProfiles/MappingProfilesForm/index.js
src/settings/MappingProfiles/NewMappingProfileFormRoute/NewMappingProfileFormRoute.js
test/bigtest/network/scenarios/fetch-job-executions-success.js
test/bigtest/tests/jobLogs-test.js
test/bigtest/tests/mapping-profiles/mappingProfiles-test.js

- Add transformations saving. [Story](https://issues.folio.org/browse/UIDEXP-105)
- Add error handling for mapping profile saving. [Story](https://issues.folio.org/browse/UIDEXP-100)
- Fix random problems with tests for running jobs list

UIDEXP-105, UIDEXP-100: Add transformations saving and error handling for mapping profiles

---

translations/ui-data-export/ar.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/ru.json

Update translation strings as of 20200604T202430

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200618T161121

---

CHANGELOG.md
src/components/ProfileDetailsActionMenu/ProfileDetailsActionMenu.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
src/settings/JobProfiles/JobProfileDetailsRoute/JobProfileDetailsRoute.js
src/settings/JobProfiles/NewJobProfileRoute/NewJobProfileRoute.js
src/settings/MappingProfiles/NewMappingProfileFormRoute/NewMappingProfileFormRoute.js
src/settings/utils/useProfileHandlerWithCallout.js
test/bigtest/network/config.js
test/bigtest/tests/job-profiles/jobProfileDetails-test.js
test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetails-test.js
test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetailsRoute-test.js
test/bigtest/tests/units/settings/JopProfileDetails/interactors/JobProfileDetailsInteractor.js
translations/ui-data-export/en.json

Add job profiles deleting functionality according to the [description](https://issues.folio.org/browse/UIDEXP-111).

UIDEXP-111: Add job profiles deleting

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200723T131158

---

translations/ui-data-export/ru.json

Update translation strings as of 20200728T221039

---

CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/SearchForm.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.css
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsModal-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsSearchForm-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/TransformationsModalInteractor.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/TransformationsSearchFormInteractor.js

Implement search feature in mapping profile transformations in the scope of the [UIDEXP-130](https://issues.folio.org/browse/UIDEXP-130).

UIDEXP-130: Implement search feature in mapping profile transformations

---

CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/SearchForm.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationsField.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsForm/TransformationsForm.js
test/bigtest/tests/units/settings/MappingProfilesForm/TransformationsModal-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/interactors/TransformationsInteractor.js

Add transformations selection in modal form ([Story](https://issues.folio.org/browse/UIDEXP-71)).

UIDEXP-71: Implement transformations selection

---

CHANGELOG.md
CODESTYLEGUIDE.md
README.md

Create coding style guide document in the scope of the [UIDEXP-148](https://issues.folio.org/browse/UIDEXP-148).

UIDEXP-148: Create coding style guide document

---

CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/FolioRecordTypeField.js
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
test/bigtest/network/scenarios/fetch-mapping-profiles-success.js
test/bigtest/tests/mapping-profiles/mappingProfiles-test.js
test/bigtest/tests/units/settings/EditMappingProfileRoute/EditMappingProfileRoute-test.js
test/bigtest/tests/units/settings/JobProfilesForm/JobProfilesForm-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js
translations/ui-data-export/en.json

Add validation between selected record types and transformations on form submit. [Story](https://issues.folio.org/browse/UIDEXP-138)

UIDEXP-138: Add validation between selected record types and transformations on form submit

---

CHANGELOG.md
translations/ui-data-export/en.json

Provide translations for the mapping profile transformation field names in the scope of the [UIDEXP-151](https://issues.folio.org/browse/UIDEXP-151).

UIDEXP-151: Provide translations for the mapping profile transformation field names

---

translations/ui-data-export/fr_FR.json
translations/ui-data-export/pt_BR.json

Update translation strings as of 20200910T134908

---

CHANGELOG.md
translations/ui-data-export/en.json

Provide translations for the mapping profile transformation field names in the scope of the [UIDEXP-159](https://issues.folio.org/browse/UIDEXP-159).

UIDEXP-159: Provide translations for the mapping profile transformation field names

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20200914T140557

---

CHANGELOG.md
src/settings/MappingProfiles/EditMappingProfileRoute/EditMappingProfileRoute.js
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
test/bigtest/tests/units/settings/EditMappingProfileRoute/EditMappingProfileRoute-test.js
test/bigtest/tests/units/settings/MappingProfilesForm/MappingProfilesForm-test.js

Fix form state updating after transformations field change on mapping profile form by creating a new field and providing an initial state. [Bug](https://issues.folio.org/browse/UIDEXP-142)

UIDEXP-153: Fix form state updating after transformations field change on mapping profile form

---

translations/ui-data-export/fr_FR.json

Update translation strings as of 20200922T125348

---

CHANGELOG.md
src/components/ProfileDetailsActionMenu/ProfileDetailsActionMenu.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/index.js
src/settings/MappingProfiles/EditMappingProfileRoute/EditMappingProfileRoute.js
src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
src/settings/MappingProfiles/MappingProfileDetailsRoute/MappingProfileDetailsRoute.js
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/MappingProfiles/utils/formatMappingProfileFormInitialValues.js
src/settings/MappingProfiles/utils/index.js
src/settings/ProfileDetails/ProfileDetails.js
test/bigtest/tests/mapping-profiles/mappingProfileDetails-test.js
test/bigtest/tests/units/settings/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute-test.js
test/bigtest/tests/units/settings/DuplicateMappingProfileRoute/interactors/DuplicateMappingProfileRouteInteractor.js

Add ability to duplicate an existing mapping profile. [Story](https://issues.folio.org/browse/UIDEXP-134)

UIDEXP-134: Implement mapping profile duplicating

---

.eslintrc
CHANGELOG.md
package.json
src/components/AllJobLogsView/AllJobLogsView.js
src/components/AllJobLogsView/index.js
src/components/ChooseJobProfile/ChooseJobProfile.js
src/components/JobLogsContainer/JobLogsContainer.js
src/components/JobLogsContainer/index.js
src/components/QueryFileUploader/QueryFileUploader.js
src/components/RecentJobLogs/RecentJobLogs.js
src/components/RecentJobLogs/index.js
src/components/index.js
src/index.js
src/routes/Home.js
src/utils/constants.js
test/bigtest/helpers/OverlayContainer.js
test/bigtest/interactors/jobs/allLogsPaneInteractor.js
test/bigtest/network/scenarios/fetch-job-executions-success.js
test/bigtest/tests/units/AllJobLogs-test.js
translations/ui-data-export/en.json

Implement view all logs list in the scope of the [UIDEXP-142](https://issues.folio.org/browse/UIDEXP-142).

UIDEXP-142: Implement view all logs list

---

CHANGELOG.md
package.json
src/settings/JobProfiles/JobProfilesForm/JobProfilesForm.js
src/settings/ProfileDetails/ProfileDetails.js

[UIDEXP-157](https://issues.folio.org/browse/UIDEXP-157)
Update react-intl to v5.7.0 and fix warnings about failed prop types.

UIDEXP-157: Update react-intl to v5.7.0

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hi_IN.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/ko.json
translations/ui-data-export/pl.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20201005T202004

---

translations/ui-data-export/it_IT.json

Update translation strings as of 20201008T220807

---

translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/pt_BR.json

Update translation strings as of 20201016T144229

---

translations/ui-data-export/ar.json

Update translation strings as of 20201020T221939

---

translations/ui-data-export/ko.json

Update translation strings as of 20201026T135354

---

translations/ui-data-export/ar.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hi_IN.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/ko.json
translations/ui-data-export/pl.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20201102T140138

---

CHANGELOG.md
package.json

Update module version and changelog after bugfix v3.0.1 release in the scope of the [UIDEXP-201](https://issues.folio.org/browse/UIDEXP-201).

UIDEXP-201: Update module version and changelog after bugfix v3.0.1 release

---

translations/ui-data-export/ar.json
translations/ui-data-export/ber.json
translations/ui-data-export/ca.json
translations/ui-data-export/da.json
translations/ui-data-export/de.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_SE.json
translations/ui-data-export/en_US.json
translations/ui-data-export/es.json
translations/ui-data-export/es_419.json
translations/ui-data-export/es_ES.json
translations/ui-data-export/fr.json
translations/ui-data-export/fr_FR.json
translations/ui-data-export/he.json
translations/ui-data-export/hi_IN.json
translations/ui-data-export/hu.json
translations/ui-data-export/it_IT.json
translations/ui-data-export/ja.json
translations/ui-data-export/ko.json
translations/ui-data-export/pl.json
translations/ui-data-export/pt_BR.json
translations/ui-data-export/pt_PT.json
translations/ui-data-export/ru.json
translations/ui-data-export/ur.json
translations/ui-data-export/zh_CN.json
translations/ui-data-export/zh_TW.json

Update translation strings as of 20201124T212804

---

CHANGELOG.md
src/components/ErrorLogsView/ErrorLogsView.js
src/components/JobLogsContainer/JobLogsContainer.js
test/bigtest/network/config.js
test/bigtest/tests/jobLogs-test.js

In scope of [UIDEXP-200](https://issues.folio.org/browse/UIDEXP-200).
Change failed job row click behavior, so it redirects to a page within same tab.

UIDEXP-200: Change failed job row click behavior, so it redirects to a page within same tab

---

CHANGELOG.md
package.json
src/settings/JobProfiles/JobProfileDetailsRoute/JobProfileDetailsRoute.js
test/bigtest/network/config.js
test/bigtest/tests/job-profiles/jobProfileDetails-test.js
test/bigtest/tests/units/AllJobLogs-test.js
test/bigtest/tests/units/settings/JopProfileDetails/JobProfileDetailsRoute-test.js

Use react-query for job profile details page in the scope of the [UIDEXP-224](https://issues.folio.org/browse/UIDEXP-224).

UIDEXP-224: Use react-query for job profile details page

---

CHANGELOG.md
package.json

In the scope of  [UIDEXP-225](https://issues.folio.org/browse/UIDEXP-225).
`ui-data-export` v4.0.0 release.

UIDEXP-225: Release v4.0.0

---

CHANGELOG.md

Update the `CHANGELOG.md` after v4.0.0 release.

UIDEXP-225: Update CHANGELOG.md

---

CHANGELOG.md
src/components/ErrorLogsView/utils/generateAffectedRecordInfo.test.js
test/bigtest/tests/units/generateAffectedRecordInfo-test.js

Handle broken BigTest test in the scope of the [UIDEXP-237](https://issues.folio.org/browse/UIDEXP-237).

UIDEXP-237: Handle broken BigTest test

---

CHANGELOG.md
package.json

Release v4.1.0 in the scope of the [UIDEXP-236](https://issues.folio.org/browse/UIDEXP-236).

UIDEXP-236: Release v4.1.0

---

.eslintrc
CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesFormContainer/processRawTransformations.js
src/settings/MappingProfiles/MappingProfilesFormContainer/processRawTransformations.test.js

https://issues.folio.org/browse/UIDEXP-242 …

UIDEXP-242 Fix Error when cloning mapping profile from the prior relases

---

src/components/FullScreenPreloader/FullScreenPreloader.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js

https://issues.folio.org/browse/UIDEXP-192 …

UIDEXP-192 Rewrite Bigtest tests for duplicate mapping profile with jest/react-testing-library

---

src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.test.js

https://issues.folio.org/browse/UIDEXP-196 …

UIDEXP-196: Rewrite Bigtest tests for mapping profile details with jest/react-testing-library

---

src/components/ErrorLogsView/ErrorLogsView.test.js

https://issues.folio.org/browse/UIDEXP-191 …

UIDEXP-191 Rewrite Bigtest tests for error logs with jest/react-testing-library

---

src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.test.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
test/helpers/translationsProperties.js
test/jest/__mock__/stripesIcon.mock.js

https://issues.folio.org/browse/UIDEXP-195 …

UIDEXP-195: Rewrite Bigtest tests for job profile details with jest/react-testing-library

---

src/components/QueryFileUploader/QueryFileUploader.css
src/components/QueryFileUploader/QueryFileUploader.js
test/bigtest/tests/queryFileUploader-test.js

https://issues.folio.org/browse/UIDEXP-251 …

UIDEXP-251 Update QueryFileUploader.js after changing API in STDTC-40

---

package.json
test/jest/babel.config.js

https://issues.folio.org/browse/UIDEXP-112 …

UIDEXP-112 Job profile – edit existing profile

---

CHANGELOG.md
src/components/MultiColumnList/GridRow/GridRow.js
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.test.js
test/jest/babel.config.js

https://issues.folio.org/browse/UIDEXP-214 …

UIDEXP-214: Add aria-label in mapping profile transformations list

---

CHANGELOG.md
src/settings/JobProfiles/CreateJobProfileRoute/CreateJobProfileRoute.js
src/settings/JobProfiles/DuplicateJobProfileRoute/DuplicateJobProfileRoute.js
src/settings/JobProfiles/DuplicateJobProfileRoute/DuplicateJobProfileRoute.test.js
src/settings/JobProfiles/DuplicateJobProfileRoute/index.js
src/settings/JobProfiles/EditJobProfileRoute/EditJobProfileRoute.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
src/settings/JobProfiles/JobProfileDetailsRoute/JobProfileDetailsRoute.js
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.test.js
src/settings/JobProfiles/JobProfilesFormContainer/JobProfilesFormContainer.js
src/settings/JobProfiles/test/setup.js
src/settings/MappingProfiles/utils/mappingProfiles.js
src/settings/MappingProfiles/utils/utils.test.js
src/settings/utils/useJobProfileData.js
translations/ui-data-export/en.json
translations/ui-data-export/en_GB.json
translations/ui-data-export/en_US.json

https://issues.folio.org/browse/UIDEXP-113 …

UIDEXP-113 Job profile – duplicate existing profile

---

CHANGELOG.md
src/components/ErrorLogsView/ErrorLogsView.js

https://issues.folio.org/browse/UIDEXP-259 …

UIDEXP-259:The list of errors is truncated

---

CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesForm/FolioRecordTypeField/utils/constants.js
src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.js
src/settings/ProfileDetails/ProfileDetails.js
src/settings/utils/useProfileHandlerWithCallout.js

https://issues.folio.org/browse/UIDEXP-216 …

UIDEXP-216 Refactor away from SafeHTMLMessage

---

package.json

https://issues.folio.org/browse/UIDEXP-235 …

UIDEXP-235 refactor away from react-intl-safe-html

---

CHANGELOG.md
src/components/QueryFileUploader/QueryFileUploader.js
translations/ui-data-export/en.json

https://issues.folio.org/browse/UIDEXP-271 …

UIDEXP-271 Implement user notification when response after uploading file is 413

---

CHANGELOG.md
src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.js
src/settings/JobProfiles/DuplicateJobProfileRoute/DuplicateJobProfileRoute.test.js
src/settings/JobProfiles/JobProfilesForm/JobProfilesForm.js
src/settings/JobProfiles/JobProfilesFormContainer/JobProfilesFormContainer.js
src/settings/JobProfiles/test/setup.js

https://issues.folio.org/browse/UIDEXP-277 …

UIDEXP-277 Data export UI cleanup

---

src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.test.js
src/settings/JobProfiles/JobProfileDetailsRoute/JobProfileDetailsRoute.test.js
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
translations/ui-data-export/en.json

https://issues.folio.org/browse/UIDEXP-277 …

UIDEXP-277 TCP/IP UI cleanup

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js

https://issues.folio.org/browse/UIDEXP-280 …

UIDEXP-280 "Undefined" value display at "Run by" column when user has  no "First name" value.

---

CHANGELOG.md
src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/SearchForm/SearchForm.js

https://issues.folio.org/browse/UIDEXP-270 …

UIDEXP-270 The search box is reset after updating filter in the Select transformations

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIDEXP-276 …

UIDEXP-276: replace babel-eslint with @babel/eslint-parser

---

CHANGELOG.md
package.json

[UIDEXP-283](https://issues.folio.org/browse/UIDEXP-283) …

Release v5.2.1

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIDEXP-285 …

Release v5.2.2

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIDEXP-287 …

Release v5.2.3

---

CHANGELOG.md
src/components/ErrorLogsView/ErrorLogsView.js
src/components/JobLogsContainer/JobLogsContainer.js

[UIDEXP-297](https://issues.folio.org/browse/UIDEXP-297) …

UIDEXP-297: Gracefully handle missing data in the exported jobs log

---

CHANGELOG.md
src/components/AllJobLogsView/CustomQueryBuilder.test.js
src/components/Jobs/Jobs.test.js
src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.test.js
src/components/RecentJobLogs/RecentJobLogs.test.js
src/index.test.js
src/settings/DataExportSettings/DataExportSettings.test.js
src/settings/JobProfiles/DuplicateJobProfileRoute/DuplicateJobProfileRoute.test.js
src/settings/JobProfiles/EditJobProfileRoute/EditJobProfileRoute.test.js
src/settings/MappingProfiles/MappingProfileDetailsRoute/MappingProfileDetailsRoute.test.js
src/utils/downloadFileByLink.test.js

https://issues.folio.org/browse/UIDEXP-296 …

 UIDEXP-296  Increase unit test code coverage for ui-data-export

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.css
src/components/JobLogsContainer/JobLogsContainer.js

https://issues.folio.org/browse/UIDEXP-141 …

UIDEXP-141: Change exported file names to the hyperlink color

---

CHANGELOG.md
package.json

[UIDEXP-302](https://issues.folio.org/browse/UIDEXP-302) …

UIDEXP-302: bump stripes to 8.0.0 for Orchid/2023-R1

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIDEXP-305 …

UIDEXP-305 A result is not displayed in list of permissions after clicking on the 'Search' button

---

CHANGELOG.md
src/components/ChooseJobProfile/ChooseJobProfilePage.test.js
src/components/ErrorLogsView/ErrorLogsView.test.js
src/components/Jobs/Jobs.test.js
src/settings/JobProfiles/CreateJobProfileRoute/CreateJobProfileRoute.test.js
src/settings/JobProfiles/DuplicateJobProfileRoute/DuplicateJobProfileRoute.test.js
src/settings/JobProfiles/EditJobProfileRoute/EditJobProfileRoute.test.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.test.js
src/settings/JobProfiles/test/setup.js
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.test.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
src/settings/MappingProfiles/EditMappingProfileRoute/EditMappingProfileRoute.test.js
src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.test.js
src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/MappingProfilesTransformationsModal.test.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/TransformationFieldGroup/TransformationFieldGroup.js
src/settings/MappingProfiles/test/setup.js

https://issues.folio.org/browse/UIDEXP-311 …

UIDEXP-311 Something went wrong during creation new field mapping profile

---

src/components/AllJobLogsView/AllJobLogsView.js

[UIDEXP-314](https://issues.folio.org/browse/UIDEXP-314) …

UIDEXP-314: Missing pagination on the View all page

---

CHANGELOG.md
translations/ui-data-export/en.json

Rename Settings (data-export): display list of settings pages to Settings (Data export): display list of settings pages
[UIDEXP-308](https://issues.folio.org/browse/UIDEXP-308)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

UIDEXP-308: Rename Settings (data-export): display list of settings pages to Settings (Data export): display list of settings pages

---

src/components/JobLogsContainer/JobLogsContainer.js
src/utils/constants.js

https://issues.folio.org/browse/UIDEXP-323 …

UIDEXP-323 Add fixed widths to columns

---

src/components/AllJobLogsView/AllJobLogsView.js
src/components/AllJobLogsView/CustomQueryBuilder.js
src/components/ChooseJobProfile/ChooseJobProfile.js

[UIDEXP-324](https://issues.folio.org/browse/UIDEXP-324) …

UIDEXP-324: Incorrect sorting by “Run by” column on the “View all” page

---

CHANGELOG.md
src/components/AllJobLogsView/AllJobLogsView.js

UIDEXP-331: Date filters cleanup
[UIDEXP-331](https://issues.folio.org/browse/UIDEXP-331) …

UIDEXP-331: Date filters cleanup

---

CHANGELOG.md
package.json

Depend on a specific version of react-virtual-auto-sizer
[UIDEXP-325](https://issues.folio.org/browse/UIDEXP-325)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …

UIDEXP-325: depend on a specific version of react-virtual-auto-sizer

---

CHANGELOG.md
src/components/AllJobLogsView/AllJobLogsView.js
src/components/JobLogsContainer/JobLogsContainer.js
src/components/RecentJobLogs/RecentJobLogs.js
src/utils/constants.js
translations/ui-data-export/en.json

https://issues.folio.org/browse/UIDEXP-330 …

UIDEXP-330 Add Started running column to Logs

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js
test/jest/__new_mock__/reactIntl.mock.js

[UIDEXP-339](https://issues.folio.org/browse/UIDEXP-339) …

UIDEXP-339: DATA EXPORT: format numbers in "totalRecords" columns

---

CHANGELOG.md
src/components/JobLogsContainer/JobLogsContainer.js
test/jest/__new_mock__/reactIntl.mock.js

[UIDEXP-342](https://issues.folio.org/browse/UIDEXP-342) …

UIDEXP-342: DATA EXPORT: format numbers in "Exported" and "Failed" columns

---

src/components/Jobs/RunningJobs/ItemFormatter/ItemFormatter.test.js
src/components/Jobs/RunningJobs/JobDetails/JobDetails.js

[UIDEXP-337](https://issues.folio.org/browse/UIDEXP-337) …

UIDEXP-337: Display duplicate SRS records in the Failed column

---

CHANGELOG.md
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.js
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.test.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.js

[UIDEXP-343](https://issues.folio.org/browse/UIDEXP-343) …

UIDEXP-343: Update HTML page title for duplicating mapping profile

---

CHANGELOG.md
translations/ui-data-export/en.json

Provide user friendly error in data export log when multiple SRS records are are linked to one instance
[UIDEXP-345](https://issues.folio.org/browse/UIDEXP-345)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, …

UIDEXP-345: Provide user friendly error in data export log when multiple SRS records are are linked to one instance

---

CHANGELOG.md
src/components/Jobs/RunningJobs/JobDetails/JobDetails.js

[UIDEXP-347](https://issues.folio.org/browse/UIDEXP-347) …

UIDEXP-347: Progress bar displays more than 100% for the records with SRS duplicates

---

CHANGELOG.md
src/components/AllJobLogsView/AllJobLogsView.js

[UIDEXP-328](https://issues.folio.org/browse/UIDEXP-328) …

UIDEXP-328: Filter by job profiles from the completed jobs

---

package.json
src/components/ProfileDetailsActionMenu/ProfileDetailsActionMenu.js
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

UIDEXP-304: Need new permission(s) to view Data Export settings in UI

---

CHANGELOG.md
src/components/AllJobLogsView/AllJobLogsView.js
src/components/AllJobLogsView/AllJobLogsView.test.js
test/bigtest/network/scenarios/fetch-job-executions-success.js

https://folio-org.atlassian.net/browse/UIDEXP-370
We pass `showUsers` in filters to show `Selection` instead of modal. Also, update the endpoint to get `users`.

UIDEXP-370: Add User look-up filter for existing jobs to Logs page

---

CHANGELOG.md
src/components/AllJobLogsView/CustomQueryBuilder.js
src/components/AllJobLogsView/CustomQueryBuilder.test.js

https://folio-org.atlassian.net/browse/UIDEXP-372
Here we fixed logic of building date range filter query

UIDEXP-372: Apply tenant date-time when filter data export logs by date on View all page

---

CHANGELOG.md
src/components/Jobs/RunningJobs/JobDetails/JobDetails.js

https://folio-org.atlassian.net/browse/UIDEXP-373
We removed part about `today` in `RunningJobs`

UIDEXP-373: Time Reported on the Progress Display

---

translations/ui-data-export/en.json

https://folio-org.atlassian.net/browse/UIDEXP-371
Small fix of translation for existing story

UIDEXP-371: Display error messages instead of error codes in Data export

---

CHANGELOG.md
package.json
src/components/AllJobLogsView/AllJobLogsView.js
src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.js
test/bigtest/network/scenarios/fetch-mapping-profiles-success.js

https://folio-org.atlassian.net/browse/UIDEXP-375
Here we added details mapping profiles with suppressed fields.
https://github.com/folio-org/ui-data-export/assets/72550466/6f84cdae-4474-4801-89f2-613ffd5084ce

UIDEXP-375: Suppressing fields on export - integrate with BE

---

CHANGELOG.md
translations/ui-data-export/en.json

https://folio-org.atlassian.net/browse/UIDEXP-294
Here we added new translations keys

UIDEXP-294: Update translation file with item's circulation notes

---

CHANGELOG.md
src/components/ChooseJobProfile/ChooseJobProfile.js
src/components/ChooseJobProfile/ChooseJobProfileSelect/ChooseJobProfileSelect.js
src/components/ErrorLogsView/utils/generateAffectedRecordInfo.js
src/components/QueryFileUploader/QueryFileUploader.js
src/settings/MappingProfiles/MappingProfilesForm/MappingProfilesForm.js
src/utils/validation.js
translations/ui-data-export/en.json

https://folio-org.atlassian.net/browse/UIDEXP-378
Here we improved validation for `suppression field`
https://github.com/folio-org/ui-data-export/assets/72550466/88e133a5-7187-47ad-bdf1-3c7129c98372

UIDEXP-378: Improve field suppression validation

---

CHANGELOG.md
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.test.js
translations/ui-data-export/en.json

After this PR merged - translations for errors will be updated. Refs [UIDEXP-381](https://folio-org.atlassian.net/browse/UIDEXP-381)
Before 
After

UIDEXP-381 Error message  in error " Logs", if the user does not have the affiliation with the tenant

---

CHANGELOG.md
package.json
src/components/QueryFileUploader/QueryFileUploader.js
src/settings/JobProfiles/JobProfilesContainer/JobProfilesContainer.js
src/settings/MappingProfiles/MappingProfilesContainer/MappingProfilesContainer.js
src/settings/ProfileDetails/ProfileDetails.js
translations/ui-data-export/en.json

https://folio-org.atlassian.net/browse/UIDEXP-387
Here we made clean up and small refactor of data-export permissions

UIDEXP-387: Data export permission cleanup

---

CHANGELOG.md
package.json
src/components/ChooseJobProfile/ChooseJobProfilePage.test.js
src/settings/JobProfiles/JobProfileDetails/JobProfileDetails.test.js
src/settings/MappingProfiles/CreateMappingProfileFormRoute/CreateMappingProfileFormRoute.test.js
src/settings/MappingProfiles/DuplicateMappingProfileRoute/DuplicateMappingProfileRoute.test.js
src/settings/MappingProfiles/MappingProfileDetails/MappingProfileDetails.test.js
src/settings/MappingProfiles/MappingProfilesFormContainer/MappingProfilesFormContainer.test.js
src/settings/MappingProfiles/MappingProfilesTransformationsModal/TransformationsField/processTransformations.js
translations/ui-data-export/en.json

While it's helpful for reviewers to help identify potential problems, ensuring that it's …

UIDEXP-398 Clean up permissions
